<?php
require_once("Includes/Functions.php");
require_once("Includes/Sessions.php");
 $_SESSION["User_ID"]=null;
 $_SESSION["Username"]=null;
 $_SESSION["AdminName"]=null;
session_destroy();
Redirect_to("Login.php");
 ?>